// List of countries as seen on onlyguider.com/near-me
const countryList = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Ireland",
  "Switzerland",
  "Austria",
  "Belgium",
  "New Zealand",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Portugal",
  "Greece",
  "Turkey",
  "Russia",
  "Ukraine",
  "South Africa",
  "India",
  "Japan",
  "South Korea",
  "China",
  "Singapore",
  "Thailand",
  "Malaysia",
  "Philippines",
  "Indonesia",
  "Vietnam",
  "Hong Kong",
  "Israel",
  "Saudi Arabia",
  "United Arab Emirates",
  "Egypt",
  "Morocco",
  "Nigeria",
  "Kenya"
];

export default countryList; 